baseURL = "https://jacaranda.ml"
title = "Jacaranda Analytics"
enableRobotsTXT = true
enableEmoji = true
theme = "hugo-theme-jane"

paginate = 10
rssLimit = 20             
disqusShortname = ""      
googleAnalytics = ""      
copyright = ""            

defaultContentLanguage = "en"           

PygmentsCodeFences = true
PygmentsStyle = "monokai"

[languages.en]
  languageCode = "en"

[author]
  name = "Jacaranda Analytics"    
  url = "https://jacaranda.ml"        

[sitemap]               
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]          
  name = "About"
  weight = 10
  identifier = "about"
  url = "/about"
  

[[menu.main]]
  name = "Posts"
  weight = 20
  identifier = "post"
  url = "/post/"

[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "Categories"
  weight = 40
  identifier = "categories"
  url = "/categories/"


[params]
  since = "2022"          
  homeFullContent = false  
  rssFullContent = true     

  logoTitle = "Jacaranda Analytics"     
  keywords = ["theme","jane"]
  description = "Jacaranda Analytics"

  dateFormatToUse = "2006-01-02"
  toc = true                     
  photoswipe = true 
  customCSS = ["custom.css"]            # if ['custom.css'], load '/static/css/custom.css' file
  customJS = []             # if ['custom.js'], load '/static/js/custom.js' file


  [params.social]                 
    a-github = "https://github.com/orgs/jacaranda-analytics/repositories"
